services:
  - type: worker  # Important: worker, not web
    name: gpt-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    pythonVersion: 3.11  # Match your bot's Python version
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "YOUR_TELEGRAM_BOT_TOKEN"
      - key: OPENAI_API_KEY
        value: "YOUR_OPENAI_API_KEY"
