services:
  - type: web
    name: telegram-chatgpt-bot
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
